#pragma once

#include "LightsDriver.h"
#include "LightsManager.h"
#include "HIDHelper.h"

#include <cstdint>
#include <string.h>

#define SNEK_VID 0x2e8a
#define SNEK_PID 0x10a8
#define SNEK_NUMOF_LIGHTS 32

// the first byte of the buffer is a static report id.
#define SNEK_REPORT_ID 0x01
#define SNEK_LIGHTING_INTERFACENUM 0x02

// all indicies contain their respective 573 pinouts
enum SnekLightIndex
{
    SNEK_LIGHTINDEX_REPORT_ID = 0,

    SNEK_LIGHTINDEX_CN10_FL1,
    SNEK_LIGHTINDEX_CN10_FL2,
    SNEK_LIGHTINDEX_CN10_FL3,
    SNEK_LIGHTINDEX_CN10_FL4,
    SNEK_LIGHTINDEX_CN10_FL5,
    SNEK_LIGHTINDEX_CN10_FL6,
    SNEK_LIGHTINDEX_CN10_FL7,
    SNEK_LIGHTINDEX_CN10_FL8,

    SNEK_LIGHTINDEX_CN13_FL1,
    SNEK_LIGHTINDEX_CN13_FL2,
    SNEK_LIGHTINDEX_CN13_FL3,
    SNEK_LIGHTINDEX_CN13_FL4,

    SNEK_LIGHTINDEX_CN14_FL1,
    SNEK_LIGHTINDEX_CN14_FL2,
    SNEK_LIGHTINDEX_CN14_FL3,
    SNEK_LIGHTINDEX_CN14_FL4,

    SNEK_LIGHTINDEX_CN12_FL1,
    SNEK_LIGHTINDEX_CN12_FL2,
    SNEK_LIGHTINDEX_CN12_FL3,
    SNEK_LIGHTINDEX_CN12_FL4,
    SNEK_LIGHTINDEX_CN12_FL5,
    SNEK_LIGHTINDEX_CN12_FL6,
    SNEK_LIGHTINDEX_CN12_FL7,
    SNEK_LIGHTINDEX_CN12_FL8,

    SNEK_LIGHTINDEX_CN11_FL1,
    SNEK_LIGHTINDEX_CN11_FL2,
    SNEK_LIGHTINDEX_CN11_FL3,
    SNEK_LIGHTINDEX_CN11_FL4,
    SNEK_LIGHTINDEX_CN11_FL5,
    SNEK_LIGHTINDEX_CN11_FL6,
    SNEK_LIGHTINDEX_CN11_FL7,
    SNEK_LIGHTINDEX_CN11_FL8,

    SNEK_LIGHTINDEX_MAX
};

// helper defines for dance mode.
#define SNEK_INDEX_DANCE_P1_START SNEK_LIGHTINDEX_CN10_FL3
#define SNEK_INDEX_DANCE_P2_START SNEK_LIGHTINDEX_CN10_FL4

#define SNEK_INDEX_DANCE_M_LR SNEK_LIGHTINDEX_CN10_FL5
#define SNEK_INDEX_DANCE_M_UR SNEK_LIGHTINDEX_CN10_FL6
#define SNEK_INDEX_DANCE_M_LL SNEK_LIGHTINDEX_CN10_FL7
#define SNEK_INDEX_DANCE_M_UL SNEK_LIGHTINDEX_CN10_FL8

#define SNEK_INDEX_DANCE_NEON SNEK_LIGHTINDEX_CN13_FL1

#define SNEK_INDEX_DANCE_P1_UP SNEK_LIGHTINDEX_CN12_FL1
#define SNEK_INDEX_DANCE_P1_DOWN SNEK_LIGHTINDEX_CN12_FL2
#define SNEK_INDEX_DANCE_P1_LEFT SNEK_LIGHTINDEX_CN12_FL3
#define SNEK_INDEX_DANCE_P1_RIGHT SNEK_LIGHTINDEX_CN12_FL4

#define SNEK_INDEX_DANCE_P2_UP SNEK_LIGHTINDEX_CN11_FL1
#define SNEK_INDEX_DANCE_P2_DOWN SNEK_LIGHTINDEX_CN11_FL2
#define SNEK_INDEX_DANCE_P2_LEFT SNEK_LIGHTINDEX_CN11_FL3
#define SNEK_INDEX_DANCE_P2_RIGHT SNEK_LIGHTINDEX_CN11_FL4

class LightsDriverSnek : public LightsDriver
{
public:
    LightsDriverSnek();
    ~LightsDriverSnek() override;

    bool Connect() override;

    void Set(const LightsState *ls) override;

    void Disconnect() override;

private:
    uint8_t outputBuffer[SNEK_LIGHTINDEX_MAX];
    uint8_t prevOutputBuffer[SNEK_LIGHTINDEX_MAX];

    HIDHelper *hidHelper;
};